// Special ammo, mode restrictions, combat effects and the eight-level Armory.
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),errors=[],checks=[];
  const p=await b.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));
  await p.goto('http://localhost:8080/debug.html?debug=1');
  const out=await p.evaluate(()=>{const P=__pal,report={};P.demo=false;P.pick.mode='10';P.pick.map='yard';
    const reset=cls=>{P.newGame([{id:'solo',name:'Tester',cls,cos:'',sk:''}],'');P.player.sal=30000;return P.player};
    let me=reset('soldier');const first=P.buyAmmo(me,'fire',0),s1=me.sal,same=P.buyAmmo(me,'fire',0),s2=me.sal,
      invalid=P.buyAmmo(me,'shock',1),switchOk=P.buyAmmo(me,'shock',0),s3=me.sal;
    report.buy={first,same,invalid,switchOk,costs:[30000-s1,s1-s2,s2-s3],equipped:me.ammoEq.slice()};
    P.changeClass(me,'sniper');const second=P.buyAmmo(me,'fire',1),s4=me.sal,duplicate=P.buyAmmo(me,'fire',0),third=P.buyAmmo(me,'blast',2);
    P.changeClass(me,'soldier');report.slots={second,secondCost:s3-s4,duplicate,third,afterClass:me.ammoEq.slice()};
    me=reset('soldier');for(const id of['d','r','g','a','n'])for(let i=0;i<8;i++)P.buyUpgrade(me,id);
    for(let i=0;i<8;i++)P.buyUpgrade(me,'dell');
    report.caps={levels:{...me.up},dell:P.game.dellLv,damage:+(me.gun.dmg/P.CLASSES.soldier.gun.dmg).toFixed(3),cd:+(me.gun.cd/P.CLASSES.soldier.gun.cd).toFixed(3),range:+(me.gun.range/P.CLASSES.soldier.gun.range).toFixed(3),speed:+(me.gun.speed/P.CLASSES.soldier.gun.speed).toFixed(3),hp:me.max,stock:me.maxN,blast:+me.blast.toFixed(3)};
    me=reset('soldier');for(let i=0;i<P.walls.length;i++)P.walls[i]=null;
    const sh=P.spawnEnemyAt('shield',8.5,7.5);sh.aim={x:-1,y:0};sh.speed=0;me.x=7.5;me.y=7.5;
    const hp=sh.hp;P.fire(me,0,0,me.gun);P.updateBulletsHook(.08);const blocked=hp-sh.hp;
    me.ammoEq=['ap',''];P.fire(me,0,0,me.gun);P.updateBulletsHook(.08);report.shield={blocked,penetrated:+(hp-sh.hp).toFixed(2)};
    const a=P.spawnEnemyAt('rifle',5.5,5.5),near=P.spawnEnemyAt('rifle',6,5.5),far=P.spawnEnemyAt('rifle',9,9);
    for(const e of[a,near,far]){e.speed=0;e.cd=99}const hpA=a.hp,hpNear=near.hp,hpFar=far.hp;
    P.ammoHit(a,{own:'solo',shot:800,ammo:[['fire',0],['blast',0],['shock',0]]});const once=a.hp;
    P.ammoHit(a,{own:'solo',shot:800,ammo:[['fire',0],['blast',0],['shock',0]]});
    report.effects={burnT:a.burnT,blastPrimary:+(hpA-a.hp).toFixed(2),blastNear:+(hpNear-near.hp).toFixed(2),farDamage:hpFar-far.hp,slowPrimary:a.slowPct,slowNear:near.slowPct,slowFar:far.slowPct,once:a.hp===once};
    P.game.mode='5';P.newGame([{id:'solo',name:'Tester',cls:'soldier',cos:'',sk:''},{id:'b',name:'Rival',cls:'soldier',cos:'',sk:''}],'base');
    me=P.player;me.sal=1000;report.pvp={buy:P.buyAmmo(me,'fire',0),equipped:me.ammoEq.slice()};P.renderArmory();report.pvp.rows=document.querySelectorAll('#armRows .arow').length;
    return report});
  assert.deepEqual(out.buy,{first:true,same:true,invalid:false,switchOk:true,costs:[150,0,75],equipped:['shock','']});checks.push('purchase and switch prices');
  assert.deepEqual(out.slots,{second:true,secondCost:150,duplicate:false,third:false,afterClass:['shock','']});checks.push('sniper cap and class switch');
  assert.deepEqual(out.caps.levels,{d:8,r:8,g:8,a:8,n:8});assert.equal(out.caps.dell,8);assert.equal(out.caps.damage,2);assert.equal(out.caps.cd,.5);assert.equal(out.caps.range,1.6);assert.equal(out.caps.speed,1.5);assert.equal(out.caps.hp,201);assert.equal(out.caps.stock,7);assert.equal(out.caps.blast,1.4);checks.push('level-eight caps');
  assert.equal(out.shield.blocked,0);assert.ok(out.shield.penetrated>5&&out.shield.penetrated<7);checks.push('frontal shield piercing');
  assert.equal(out.effects.burnT,3);assert.equal(out.effects.blastPrimary,8);assert.ok(out.effects.blastNear>0);assert.equal(out.effects.farDamage,0);assert.equal(out.effects.slowPrimary,.25);assert.equal(out.effects.slowNear,.25);assert.equal(out.effects.slowFar,undefined);assert.equal(out.effects.once,true);checks.push('burn blast and slow');
  assert.deepEqual(out.pvp,{buy:false,equipped:['',''],rows:5});checks.push('ammo absent in Base Battle');
  const more=await p.evaluate(()=>{const P=__pal,r={modes:{}};P.demo=false;
    for(const mode of['5','10','endless','blitz']){P.pick.mode=mode;P.newGame([{id:'solo',name:'Tester',cls:'soldier',cos:'',sk:''}],'');P.player.sal=200;r.modes[mode]=P.buyAmmo(P.player,'fire',0)}
    P.newGame([{id:'solo',name:'Tester',cls:'soldier',cos:'',sk:''},{id:'b',name:'Rival',cls:'soldier',cos:'',sk:''}],'ffa');P.player.sal=200;r.ffa=P.buyAmmo(P.player,'fire',0);
    P.pick.mode='5';P.newGame([{id:'solo',name:'Tester',cls:'grenadier',cos:'',sk:''}],'');const me=P.player,e=P.spawnEnemyAt('rifle',5.5,5.5);e.speed=0;e.cd=99;
    me.ammoEq=['blast',''];me.aim={x:1,y:0};P.shoot(me,me.gun,0);r.pelletShotCount=new Set(P.bullets.map(b=>b.shot)).size;r.pelletAmmo=P.bullets.every(b=>b.ammo[0][0]==='blast');P.bullets.length=0;
    const hp=e.hp,shot={own:'solo',shot:2000,ammo:[['blast',0]]};for(let i=0;i<7;i++)P.ammoHit(e,shot);
    r.pellets=+(hp-e.hp).toFixed(2);P.ammoHit(e,{...shot,shot:2001});r.cooldown=e.hp===hp-8;
    P.game.time+=.41;P.ammoHit(e,{...shot,shot:2002});r.afterCooldown=+(hp-e.hp).toFixed(2);
    P.spawnBoss('butcher');const b=P.enemies.find(x=>x.type==='boss');if(b){P.ammoHit(b,{own:'solo',shot:2003,ammo:[['shock',4]]});r.bossSlow=b.slowPct}
    const dying=P.spawnEnemyAt('rifle',6.5,6.5);dying.hp=5;dying.speed=0;dying.cd=99;
    const before=me.kills;P.ammoHit(dying,{own:'solo',shot:2004,ammo:[['fire',0]]});P.updateEnemies(.5);r.burnKill=me.kills-before;
    P.newGame([{id:'solo',name:'Tester',cls:'sniper',cos:'',sk:''}],'');const sn=P.player;sn.sal=500;P.buyAmmo(sn,'ap',0);P.buyAmmo(sn,'fire',1);sn.x=7.5;sn.y=7.5;
    for(let i=0;i<P.walls.length;i++)P.walls[i]=null;const shield=P.spawnEnemyAt('shield',8.5,7.5);shield.aim={x:-1,y:0};shield.speed=0;const shieldHp=shield.hp;
    P.fire(sn,0,0,sn.gun);P.updateBulletsHook(.08);r.dual={damage:+(shieldHp-shield.hp).toFixed(2),burn:shield.burnT};
    return r});
  assert.deepEqual(more.modes,{'5':true,'10':true,endless:true,blitz:true});assert.equal(more.ffa,false);checks.push('four eligible modes and FFA exclusion');
  assert.equal(more.pelletShotCount,1);assert.equal(more.pelletAmmo,true);assert.equal(more.pellets,8);assert.equal(more.cooldown,true);assert.equal(more.afterCooldown,16);checks.push('shotgun proc and blast cooldown');
  assert.equal(more.bossSlow,.2);assert.equal(more.burnKill,1);checks.push('boss slow cap and burn kill credit');
  assert.ok(more.dual.damage>23&&more.dual.damage<24);assert.equal(more.dual.burn,3);checks.push('sniper dual effect through shield');
  const edge=await p.evaluate(()=>{const P=__pal;P.newGame([{id:'solo',name:'Tester',cls:'soldier',cos:'',sk:''}],'');const me=P.player;me.sal=500;const r={};
    me.x=0;me.y=0;r.far=P.buyAmmo(me,'fire',0);me.x=P.core.i+.5;me.y=P.core.j+.5;me.alive=false;r.dead=P.buyAmmo(me,'fire',0);me.alive=true;P.game.phase='raid';r.raid=P.buyAmmo(me,'fire',0);P.game.phase='build';
    P.game.mode='blitz';P.game.mods=['lockdown'];P.game.wave=14;r.lockdown=P.buyAmmo(me,'fire',0);P.game.mods=[];P.game.mode='5';me.sal=149;r.poor=P.buyAmmo(me,'fire',0);r.sal=me.sal;
    const e=P.spawnEnemyAt('rifle',4.5,4.5);e.hp=e.max=1000;e.cd=999;e.speed=0;P.ammoHit(e,{own:'solo',shot:3001,ammo:[['fire',0]]});const before=P.parts.length;
    for(let i=0;i<60;i++)P.updateEnemies(1/60);r.burnDamage=+(1000-e.hp).toFixed(4);r.burnParticles=P.parts.length-before;
    P.ammoHit(e,{own:'solo',shot:3002,ammo:[['fire',4]]});P.updateEnemies(.5);P.ammoHit(e,{own:'solo',shot:3001,ammo:[['fire',0]]});r.interleaved=+e.burnT.toFixed(2);r.history=e.ammoSeen.solo.length;
    const near=[];for(let i=0;i<4;i++){const a=P.spawnEnemyAt('rifle',5+i*.3,4.5);a.speed=0;a.cd=999;near.push(a)}const hidden=P.spawnEnemyAt('rifle',4.6,4.5);hidden.burrow=true;
    P.ammoHit(e,{own:'solo',shot:3003,ammo:[['shock',0]]});r.chain=near.map(a=>!!a.slowT);r.hidden=!!hidden.slowT;
    P.newGame([{id:'solo',name:'Tester',cls:'sniper',cos:'',sk:''}],'');P.player.sal=500;P.buyAmmo(P.player,'ap',0);P.buyAmmo(P.player,'fire',1);P.changeClass(P.player,'soldier');P.changeClass(P.player,'sniper');r.returnSlots=P.player.ammoEq.slice();return r});
  assert.deepEqual([edge.far,edge.dead,edge.raid,edge.lockdown,edge.poor],[false,false,false,false,false]);assert.equal(edge.sal,149);assert.equal(edge.burnDamage,10);assert.equal(edge.burnParticles,0);assert.equal(edge.interleaved,4.5);assert.equal(edge.history,2);assert.deepEqual(edge.chain,[true,true,true,false]);assert.equal(edge.hidden,false);assert.deepEqual(edge.returnSlots,['ap','']);checks.push('purchase guards, quiet burn ticks, interleaved rounds and chain limit');
  const layout=await p.evaluate(()=>{const ov=document.getElementById('armory');ov.hidden=false;__pal.renderArmory();const first=ov.querySelector('.arow').getBoundingClientRect().top;
    ov.scrollTop=ov.scrollHeight;const last=document.getElementById('armClose').getBoundingClientRect().bottom;
    return{first,last,viewport:innerHeight,width:ov.scrollWidth,client:ov.clientWidth,rows:ov.querySelectorAll('.arow').length}});
  assert.ok(layout.first>=0&&layout.last<=layout.viewport+1&&layout.width<=layout.client+1,JSON.stringify(layout));assert.equal(layout.rows,7);checks.push('portrait upgrades fit');
  await p.click('#armAmmoTab');assert.equal(await p.locator('#armRows .ammoRow').count(),4);assert.equal(await p.locator('[data-arm-slot]').count(),2);
  await p.evaluate(()=>document.getElementById('armory').scrollTop=0);await p.screenshot({path:__dirname+'/out/ammo_portrait.png'});
  await p.setViewportSize({width:844,height:390});await p.waitForFunction(()=>document.getElementById('armory').getBoundingClientRect().height<=innerHeight+1);const landscape=await p.evaluate(()=>{const ov=document.getElementById('armory');ov.scrollTop=0;const first=ov.querySelector('.arow').getBoundingClientRect().top;ov.scrollTop=ov.scrollHeight;return{first,last:document.getElementById('armClose').getBoundingClientRect().bottom,width:ov.scrollWidth,client:ov.clientWidth}});
  assert.ok(landscape.first>=0&&landscape.last<=391&&landscape.width<=landscape.client+1,JSON.stringify(landscape));await p.screenshot({path:__dirname+'/out/ammo_landscape.png'});checks.push('landscape ammo fits');
  assert.deepEqual(errors,[]);await b.close();console.log(JSON.stringify({checks,out}));console.log('errors: none');
})().catch(e=>{console.error(e);process.exit(1)});
