const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM}),errors=[],checks=[];
 const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,hasTouch:true,isMobile:true});p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{const original=Math.random;Math.random=()=>window.__caseRandom??original()});await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>__pal);await p.evaluate(()=>{__pal.cfg.music=0;__pal.showPage('locker');__pal.locker.cases=4;__pal.saveLocker();__pal.renderLocker()});assert.ok(await p.isDisabled('[data-open5=supply]'));await p.evaluate(()=>{__pal.locker.cases=15;__pal.saveLocker();__pal.renderLocker()});
 await p.click('[data-open5=supply]');await p.evaluate(()=>__pal.openCaseUI('supply',5));await p.waitForFunction(()=>__pal.caseSession?.results?.length===5);const committed=await p.evaluate(()=>({cases:__pal.locker.cases,owned:__pal.locker.owned,shards:__pal.locker.shards,eq:__pal.locker.eq,receipt:__pal.locker.lastOpening}));assert.equal(committed.cases,10);assert.equal(committed.receipt.results.length,5);assert.ok(await p.isDisabled('[data-open=supply]'));await p.click('#caseIntro');await p.waitForFunction(()=>document.querySelectorAll('#caseOv .reel').length===5);
 const geometry=await p.evaluate(()=>{const rows=[...document.querySelectorAll('#caseOv .reelWrap')].map(el=>{const r=el.getBoundingClientRect();return {left:r.left,width:r.width,top:r.top,bottom:r.bottom}});return {rows,viewport:innerHeight}});assert.equal(new Set(geometry.rows.map(r=>r.left+':'+r.width)).size,1);assert.ok(geometry.rows.every(r=>r.bottom<geometry.viewport));await p.screenshot({path:__dirname+'/out/case-five-spin.png'});
 await p.waitForSelector('#caseResult:not([hidden])');const result=await p.evaluate(()=>({rows:[...document.querySelectorAll('.caseResultRow')].map(el=>el.dataset.item),landed:[...document.querySelectorAll('#caseOv .reel')].map(el=>el.querySelectorAll('.item')[el.dataset.win].dataset.item),eq:__pal.locker.eq,centers:[...document.querySelectorAll('#caseOv .reel')].map(el=>{const r=el.querySelectorAll('.item')[el.dataset.win].getBoundingClientRect(),w=el.parentElement.getBoundingClientRect();return{error:r.left+r.width/2-w.left-w.width/2,width:r.width,step:el.querySelectorAll('.item')[1].offsetLeft-el.querySelectorAll('.item')[0].offsetLeft,transform:getComputedStyle(el).transform}})}));assert.ok(result.centers.every(x=>Math.abs(x.error)<2),'actual winning items align with the center marker');assert.deepEqual(result.rows,committed.receipt.results.map(r=>r.id));assert.deepEqual(result.landed,result.rows);assert.deepEqual(result.eq,committed.eq);await p.screenshot({path:__dirname+'/out/case-five-results.png'});await p.click('#caseDone');assert.equal(await p.evaluate(()=>__pal.caseSession),null);assert.equal(await p.locator('#caseRows>*').count(),0);checks.push('five aligned phone reels, committed winners, repeated-click lock and no auto-equip');
 await p.click('[data-open5=supply]');await p.waitForFunction(()=>__pal.caseSession?.results?.length===5);const beforeReload=await p.evaluate(()=>({receipt:__pal.locker.lastOpening,cases:__pal.locker.cases,shards:__pal.locker.shards}));await p.reload();await p.waitForFunction(()=>__pal);await p.evaluate(()=>__pal.showPage('locker'));await p.waitForFunction(()=>__pal.caseSession?.results?.length===5);const afterReload=await p.evaluate(()=>({receipt:__pal.locker.lastOpening,cases:__pal.locker.cases,shards:__pal.locker.shards}));assert.deepEqual(afterReload,beforeReload);await p.click('#caseSkip');await p.waitForSelector('#caseResult:not([hidden])');await p.click('#caseDone');checks.push('reload resumes exact local receipt without consumption or reroll');
 await p.emulateMedia({reducedMotion:'reduce'});await p.click('[data-open5=supply]');await p.waitForSelector('#caseResult:not([hidden])');assert.equal(await p.locator('.caseResultRow').count(),5);await p.keyboard.press('Escape');assert.equal(await p.locator('#caseOv').isVisible(),false);assert.ok((await p.evaluate(()=>__pal.caseArtStats)).entries<=64);checks.push('reduced motion, Escape/controller-back path and bounded art cache');
 await p.evaluate(()=>{window.__caseRandom=.15;const it=__pal.rollCase('supply');__pal.locker.owned=__pal.locker.owned.filter(id=>id!==it.id);__pal.locker.cases=5;__pal.saveLocker();__pal.renderLocker()});await p.click('[data-open5=supply]');await p.waitForFunction(()=>__pal.caseSession?.results?.length===5);const duplicates=await p.evaluate(()=>__pal.caseSession.results.map(r=>({id:r.it.id,dup:r.dup,shards:r.shards})));assert.equal(new Set(duplicates.map(r=>r.id)).size,1);assert.deepEqual(duplicates.map(r=>r.dup),[false,true,true,true,true]);await p.click('#caseSkip');await p.waitForSelector('#caseResult:not([hidden])');await p.click('#caseDone');await p.evaluate(()=>window.__caseRandom=null);checks.push('local rolls resolve ownership in order for four within-batch duplicates');
 // Simulated account transport commits once but loses the first response. The server implementation is tested separately.
 const UID='55555555-5555-4555-8555-555555555555',responses=[];let receipt=null,remaining=10,calls=0;
 await p.route(/\/rest\/v1\/rpc\/open_cases_v096[24]$/,async route=>{const request=route.request().postDataJSON();responses.push(request);calls++;if(!receipt){remaining-=request.p_quantity;receipt=Array.from({length:5},(_,i)=>({item:{id:'trail:gold',cat:'trail',key:'gold',name:'Gold',rarity:'r'},dup:i>0,shards:i>0?3:0}))}if(calls===1){await route.abort();return}await route.fulfill({json:{operation:request.p_operation,case:request.p_case,quantity:5,results:receipt,locker:{owned:['trail:gold'],eq:{},cases:remaining,bag:{},shards:12,st:{},skills:{}}}})});
 await p.evaluate(uid=>{__pal.acct.s={access_token:'test-session',refresh_token:'test-refresh',expires_at:Date.now()/1000+10000,user:{id:uid}};localStorage.setItem('palisade.auth.v1',JSON.stringify(__pal.acct.s));__pal.locker.cloud={id:uid};__pal.locker.cases=10;__pal.saveLocker();__pal.renderLocker()},UID);
 await p.click('[data-open5=supply]');await p.waitForSelector('#caseResume:not([hidden])');assert.equal(remaining,5);await p.reload();await p.waitForFunction(()=>__pal);await p.evaluate(()=>__pal.showPage('locker'));await p.waitForFunction(()=>__pal.caseSession?.results?.length===5);await p.click('#caseSkip');await p.waitForSelector('#caseResult:not([hidden])');assert.equal(await p.evaluate(()=>__pal.locker.cases),5);assert.equal(responses[0].p_operation,responses[1].p_operation);await p.click('#caseDone');checks.push('reload after an uncertain cloud response retries the saved operation ID and presents committed awards');
 assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/out/case-batches.json',JSON.stringify({checks,geometry,committed,result,localDuplicates:duplicates,cloudRequests:responses,errors},null,2));await b.close();console.log(checks.join('; ')+'. errors: none');
})().catch(e=>{console.error(e);process.exit(1)});
