const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM,args:['--disable-gpu','--disable-accelerated-2d-canvas']}),p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:3}),errors=[],samples=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:8080/debug.html?debug=1');await p.evaluate(()=>{__pal.cfg.music=0;__pal.cfg.volume=0;__pal.locker.cases=150;__pal.saveLocker();__pal.showPage('locker');for(const it of __pal.COS.filter(it=>it.box==='supply'))__pal.caseArtURL(it)});
 const cdp=await p.context().newCDPSession(p);await cdp.send('Performance.enable');
 for(let i=1;i<=20;i++){await p.evaluate(()=>{__pal.openCaseUI('supply',5);document.getElementById('caseIntro').click()});await p.waitForFunction(()=>document.querySelectorAll('#caseOv .reel').length===5&&__pal.caseSession?.results?.length===5);await p.click('#caseSkip');await p.waitForSelector('#caseResult:not([hidden])');await p.click('#caseDone');
  if(i%5===0){await cdp.send('HeapProfiler.collectGarbage');const metrics=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value])),state=await p.evaluate(()=>({art:__pal.caseArtStats,session:__pal.caseSession,tiles:document.querySelectorAll('#caseOv .item').length,results:document.querySelectorAll('.caseResultRow').length,intro:__pal.caseIntroOn}));assert.equal(state.session,null);assert.equal(state.tiles,0);assert.equal(state.results,0);assert.equal(state.intro,false);samples.push({batches:i,heap:metrics.JSHeapUsedSize,nodes:metrics.Nodes,...state})}
 }
 const tail=samples.slice(1).map(x=>x.heap);assert.ok(Math.max(...tail)-Math.min(...tail)<256*1024,'retained heap plateaus after art warmup');assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/out/case-memory.json',JSON.stringify({samples,errors},null,2));await b.close();console.log('Twenty repeated batches release all reel/result nodes and callbacks; warm-cache retained heap stays within 256 KB. errors: none');
})().catch(e=>{console.error(e);process.exit(1)});
