const {PGlite}=require('@electric-sql/pglite'),{citext}=require('@electric-sql/pglite/contrib/citext'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const db=new PGlite({extensions:{citext}});
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,is_anonymous boolean default false,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql stable as $$select '{"is_anonymous":false}'::jsonb$$;`);
 await db.exec(fs.readFileSync(__dirname+'/../supabase/schema.sql','utf8'));
 const U='66666666-6666-4666-8666-666666666666',OP='11111111-1111-4111-8111-111111111111',OP2='22222222-2222-4222-8222-222222222222';
 await db.exec(`insert into auth.users(id) values('${U}');set request.jwt.claim.sub='${U}';update lockers set cases=5 where user_id='${U}';update case_types set weights='{"e":100}' where id='winter';update cosmetics set catalog_version=9 where box='winter' and id<>'skin:yulemaw';update lockers set bag='{"winter":5}' where user_id='${U}'`);
 const open=async(op=OP,q=5)=>(await db.query('select open_cases_v0962($1,$2,$3::uuid) r',['winter',q,op])).rows[0].r;
 const first=await open();assert.equal(first.results.length,5);assert.deepEqual(first.results.map(x=>x.dup),[false,true,true,true,true]);assert.equal(first.locker.bag.winter,0);assert.equal(first.locker.shards,first.results.reduce((a,r)=>a+r.shards,0));assert.equal(first.locker.owned.filter(x=>x==='skin:yulemaw').length,1);
 const copies=await Promise.all(Array.from({length:8},()=>open()));for(const retry of copies){assert.ok(retry.retry);assert.deepEqual(retry.results,first.results);assert.equal(retry.locker.shards,first.locker.shards)}
 await assert.rejects(()=>open(OP,1),/different request/);await assert.rejects(()=>open(OP2),/Not enough/);assert.equal((await db.query('select count(*)::int n from private.case_openings')).rows[0].n,1);
 await db.exec(`update lockers set shards=shards+100,bag='{"winter":4}' where user_id='${U}'`);assert.equal((await open()).locker.shards,first.locker.shards+100);await assert.rejects(()=>open(OP2),/Not enough/);assert.equal((await db.query('select bag from lockers')).rows[0].bag.winter,4);
 await db.exec(`update lockers set bag='{"winter":5}' where user_id='${U}';create function private.reject_receipt() returns trigger language plpgsql as $$begin raise exception 'injected receipt failure';end$$;create trigger reject_receipt before insert on private.case_openings for each row execute function private.reject_receipt()`);
 await assert.rejects(()=>open(OP2),/injected receipt/);assert.equal((await db.query('select bag from lockers')).rows[0].bag.winter,5);assert.equal((await open()).locker.shards,first.locker.shards+100);
 await db.exec('drop trigger reject_receipt on private.case_openings');const single=await open(OP2,1);assert.equal(single.results.length,1);assert.equal(single.locker.bag.winter,4);
 assert.equal((await db.query("select has_function_privilege('anon','public.open_cases_v0962(text,integer,uuid)','execute') p")).rows[0].p,false);assert.equal((await db.query("select has_table_privilege('authenticated','private.case_openings','select') p")).rows[0].p,false);
 await db.close();console.log('Atomic five/single rolls, within-batch duplicates, eight retries, rollback, latest inventory and permissions pass. errors: none');
})().catch(e=>{console.error(e);process.exitCode=1});
