// Cosmetic art must survive every catalog item, network replay, and particle cleanup.
const {chromium}=require('playwright'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>window.__pal);await p.click('[data-go=solo]');await p.click('#startBtn');
const result=await p.evaluate(()=>{const P=__pal,failures=[],cv=document.createElement('canvas');cv.width=cv.height=256;const g=cv.getContext('2d'),mode=P.NET.mode,ingame=P.NET.inGame;P.NET.mode='host';P.NET.inGame=true;let finishers=0,tracers=0,states=0;const storage=JSON.stringify(localStorage),own=JSON.stringify(P.locker);const alphaPixels=()=>g.getImageData(0,0,256,256).data.some((v,i)=>i%4===3&&v);
for(const [id,st]of Object.entries(P.TRAILS)){for(let angle=0;angle<360;angle+=15){g.clearRect(0,0,256,256);const a=angle*Math.PI/180;g.globalAlpha=.7;g.lineWidth=3;g.strokeStyle='#123456';P.traceSeg(g,128,128,128+Math.cos(a)*60,128+Math.sin(a)*60,st,2,angle/10,false);if(!alphaPixels())failures.push('empty tracer '+id);if(Math.abs(g.globalAlpha-.7)>1e-6||g.lineWidth!==3||g.strokeStyle!=='#123456')failures.push('canvas state '+id);states++;tracers++}
// Extremely short muzzle segments must never paint behind their clipped tail.
g.clearRect(0,0,256,256);P.traceSeg(g,128,128,129,128,st,6,1,false);const data=g.getImageData(130,0,126,256).data;if(data.some((v,i)=>i%4===3&&v))failures.push('muzzle overdraw '+id);}
g.globalAlpha=1;
for(const item of P.COS.filter(c=>c.cat==='fx')){P.parts.length=0;P.NET.fxq=[];P.killFx(P.player.x,P.player.y,item.key);const burst=P.parts.find(q=>q.kind==='finish:'+item.key);if(item.key==='none'){if(P.parts.length)failures.push('none emitted');continue}if(!burst||burst.vx||burst.vy||burst.vz||burst.grav)failures.push('missing/static '+item.key);const events=JSON.parse(JSON.stringify(P.NET.fxq));P.parts.length=0;P.replayFx(events);if(!P.parts.some(q=>q.kind==='finish:'+item.key))failures.push('guest replay '+item.key);
for(const progress of [.1,.35,.75,.99]){g.clearRect(0,0,256,256);P.paintFinish(g,item.key,progress,2,128,140);if(!alphaPixels())failures.push('empty finisher '+item.key+progress)}g.clearRect(0,0,256,256);P.paintFinish(g,item.key,1,2,128,140);if(alphaPixels())failures.push('expired paint '+item.key);for(const q of P.parts)q.life=q.max*.6;P.render(1/60);finishers++;}
P.parts.length=0;for(let n=0;n<60;n++)P.killFx(P.player.x,P.player.y,'skull');const active=P.parts.filter(q=>q.kind.startsWith('finish:')).length;if(active>24||P.parts.length>600)failures.push('effect budget');for(let n=0;n<200;n++)P.update(.016);if(P.parts.some(q=>q.kind.startsWith('finish:')))failures.push('expired particles');
for(let t=0;t<20;t+=.1)for(const st of Object.values(P.TRAILS))P.traceSeg(g,10,10,150,70,st,3,t,false);if(P.cosmeticCache.tracers>64||P.cosmeticCache.glows>32)failures.push('unbounded cache');
if(JSON.stringify(localStorage)!==storage||JSON.stringify(P.locker)!==own)failures.push('cosmetics changed ownership/storage');P.NET.mode=mode;P.NET.inGame=ingame;P.NET.fxq=[];return{tracers,finishers,states,activeLimit:active,cache:P.cosmeticCache,failures}});console.log(JSON.stringify(result));fs.writeFileSync(__dirname+'/out/cosmetics.json',JSON.stringify({...result,errors},null,2));console.log('errors:',errors.length?errors:'none');if(result.failures.length||errors.length)throw new Error('Cosmetic regression failed');await b.close()})();
