// Real host-to-phone transport for all upgraded kill effect events.
const {chromium}=require('playwright'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,args:['--disable-features=WebRtcHideLocalIpsWithMdns']}),h=await b.newPage({viewport:{width:1280,height:720}}),g=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];for(const p of[h,g])p.on('pageerror',e=>errors.push(e.message));const url='http://localhost:8080/debug.html?debug=1&peerhost=127.0.0.1&peerport=9000&peerpath=/';await h.goto(url);await g.goto(url);
// v0.9.3: the host wears a new milestone outfit and a Flag Case tracer; the guest has to see both
await h.evaluate(()=>{const L=__pal.locker;L.owned.push('skin:butcher4','trail:f_pride');L.eq.skin='butcher4';L.eq.trail='f_pride'});
await h.click('[data-go=multi]');await h.fill('#mName','FX Host');await h.click('#hostBtn');await h.waitForSelector('#pg-lobby:not([hidden])');const code=await h.textContent('#lCode');await g.click('[data-go=multi]');await g.fill('#mName','FX Guest');await g.fill('#mCode',code);await g.click('#joinBtn');await g.waitForSelector('#pg-lobby:not([hidden])');await h.waitForTimeout(400);await h.click('#lStart');await g.waitForFunction(()=>__pal.NET.inGame);
const seenCos=await g.evaluate(()=>{const o=[...__pal.players.values()].find(p=>p!==__pal.player);const lk=__pal.playerLook(o);return{skin:o.cos.skin,trail:o.cos.trail,aura:lk.aura||'',fallback:JSON.stringify(__pal.parseCosT('butcher9|nohat|f_nowhere|nofx'))}});
if(seenCos.skin!=='butcher4'||seenCos.trail!=='f_pride'||seenCos.aura!=='gbutcher')errors.push('guest did not see the host\'s new outfit: '+JSON.stringify(seenCos));
if(seenCos.fallback!==JSON.stringify({skin:'std',hat:'class',trail:'std',fx:'none'}))errors.push('unknown items did not fall back: '+seenCos.fallback);
console.log('new cosmetics seen by the guest:',JSON.stringify(seenCos));
await g.evaluate(()=>{window.seenFinish=new Set();window.finishTimer=setInterval(()=>{for(const p of __pal.parts)if(p.kind.startsWith('finish:'))window.seenFinish.add(p.kind.slice(7));if(__pal.floats.some(f=>f.t==='☠'))window.seenFinish.add('skull')},8)});
const ids=await h.evaluate(()=>Object.keys(__pal.FINISH_LIFE));for(const key of ids){await h.evaluate(key=>__pal.killFx(__pal.player.x,__pal.player.y,key),key);await g.waitForFunction(key=>window.seenFinish.has(key),key,{timeout:5000})}await g.waitForTimeout(1400);const seen=await g.evaluate(()=>{clearInterval(window.finishTimer);return [...window.seenFinish]});const result={expected:ids.length,received:seen.length,effects:seen,errors};console.log(JSON.stringify(result));console.log('errors:',errors.length?errors:'none');fs.writeFileSync(__dirname+'/out/cosmetic_network.json',JSON.stringify(result,null,2));if(errors.length||seen.length!==ids.length)throw new Error('Guest effect transport failed');await b.close()})();
