// Cosmetic shot origins, unchanged projectile physics, and guest event compatibility.
const {chromium}=require('playwright'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),p=await b.newPage({viewport:{width:1600,height:1300}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>window.__pal);await p.click('[data-go=solo]');await p.click('#startBtn');
const result=await p.evaluate(()=>{const P=__pal,failures=[],classes=['soldier','sniper','grenadier','quartermaster'];let checks=0,movingChecks=0,settledChecks=0,maxTailError=0,maxAngleError=0;const oldMode=P.NET.mode,oldIn=P.NET.inGame,oldTime=P.game.time;P.NET.mode='host';P.NET.inGame=true;
const cv=document.createElement('canvas');cv.width=1600;cv.height=1300;cv.style='position:fixed;inset:0;z-index:999999;background:#b7bba7';document.body.append(cv);const g=cv.getContext('2d');g.fillStyle='#b7bba7';g.fillRect(0,0,1600,1300);
for(const [row,cls]of classes.entries()){const actor=P.makePlayer('muzzle-test','TEST',cls,0,{skin:['std','gold','neonclown','gknight'][row],hat:'class',trail:'plasma',fx:'none'});P.players.set(actor.id,actor);
P.playerLook(actor);
for(let degree=0;degree<360;degree++){const angle=degree*Math.PI/180;actor.aim={x:Math.cos(angle),y:Math.sin(angle)};actor.walk=degree*.09;P.game.time+=1/60;if(degree<240){actor.x+=Math.cos(angle+1)*.04;actor.y+=Math.sin(angle+1)*.04}P.bullets.length=0;P.flashes.length=0;P.NET.fxq=[];
P.fire(actor,angle,0,actor.gun,0);const bullet=P.bullets[0],flash=P.flashes[0],speed=actor.gun.speed,origin=P.iso(actor.x,actor.y),forward=P.iso(actor.x+actor.aim.x,actor.y+actor.aim.y),dx=forward[0]-origin[0],dy=forward[1]-origin[1],dl=Math.hypot(dx,dy),sd={x:dx/dl,y:dy/dl};
const look={...P.playerLook(actor),bolt:actor.gun.bolt?0:-1,syncRender:true},barrel=P.wardrobeBarrel(look,sd,look.walk??actor.walk),m=barrel.tip.map((v,i)=>origin[i]+v*P.u*1.18),fp=P.flashPoint(flash);if(look.gaitWeight>0)movingChecks++;else settledChecks++;
const physical=Math.abs(bullet.x-actor.x-actor.aim.x*.33)+Math.abs(bullet.y-actor.y-actor.aim.y*.33)+Math.abs(bullet.vx-actor.aim.x*speed)+Math.abs(bullet.vy-actor.aim.y*speed);if(physical>1e-8||bullet.range!==actor.gun.range||bullet.dmg!==actor.gun.dmg)failures.push('physics '+cls+degree);
const flashError=Math.hypot(m[0]-fp[0],m[1]-fp[1]);if(flashError>1e-7)failures.push('flash '+cls+degree);
const bv=[barrel.tip[0]-barrel.root[0],barrel.tip[1]-barrel.root[1]],err=Math.acos(Math.min(1,Math.max(-1,(bv[0]*sd.x+bv[1]*sd.y)/Math.hypot(...bv))))*180/Math.PI;maxAngleError=Math.max(maxAngleError,err);
bullet.x=actor.x+actor.aim.x*1.8;bullet.y=actor.y+actor.aim.y*1.8;const pts=P.tracerPoints(bullet,2),tailError=pts?Math.hypot(pts.tail[0]-m[0],pts.tail[1]-m[1]):Infinity;maxTailError=Math.max(maxTailError,tailError);if(tailError>1e-7)failures.push('tail '+cls+degree);
const wire=P.NET.fxq.find(e=>e[0]==='b'),fw=P.NET.fxq.find(e=>e[0]==='h');P.bullets.length=0;P.flashes.length=0;P.replayFx(JSON.parse(JSON.stringify([wire,fw])));if(JSON.stringify(P.bullets[0].visual)!==JSON.stringify(bullet.visual)||Math.hypot(...P.flashPoint(P.flashes[0]).map((v,i)=>v-fp[i]))>1e-7)failures.push('guest '+cls+degree);
if(degree%45===0){const col=degree/45,cx=100+col*200,cy=250+row*315,scale=4.6;g.save();g.translate(col*200,row*315);P.drawFig(g,200,300,look,scale,actor.aim,250);g.restore();const map=q=>[cx+(q[0]-origin[0])*scale/P.u,cy+(q[1]-origin[1])*scale/P.u],end=map(pts.head),c=map(pts.tail),length=Math.hypot(end[0]-c[0],end[1]-c[1]),a=c.map((v,i)=>v+(end[i]-v)*Math.min(1,55/length));g.strokeStyle='#f2ffff';g.lineWidth=2;g.beginPath();g.moveTo(...c);g.lineTo(...a);g.stroke();g.fillStyle='#fcdd75';g.beginPath();g.arc(...c,2.5,0,7);g.fill();g.fillStyle='#243c30';g.font='12px system-ui';g.textAlign='center';g.fillText(cls+' / '+degree+'°',cx,295+row*315)}checks++}
P.players.delete(actor.id)}
P.NET.mode=oldMode;P.NET.inGame=oldIn;P.game.time=oldTime;P.NET.fxq=[];P.bullets.length=0;P.flashes.length=0;if(movingChecks<800||settledChecks<200)failures.push('moving/settled coverage');
P.addGuestBullet(['b',123,1,2,3,4,0,0,0,9]);if(P.bullets[0].visual!==null)failures.push('legacy event');P.bullets.length=0;
return{checks,movingChecks,settledChecks,maxTailError,maxAngleError,failures};});await p.screenshot({path:__dirname+'/out/muzzle-angles.jpg',quality:85});fs.writeFileSync(__dirname+'/out/muzzle-check.json',JSON.stringify({...result,errors},null,2));console.log(JSON.stringify({...result,errors}));console.log('errors:',errors.length?errors:'none');if(result.failures.length||errors.length||result.maxAngleError>1.7){console.error('Error: muzzle calibration failed');process.exitCode=1;}await b.close()})();
