// Honest host / guest motion, settling, and current Locker composition. No reward or combat suite.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,args:['--disable-features=WebRtcHideLocalIpsWithMdns']}),h=await b.newPage({viewport:{width:1280,height:800}}),g=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];for(const p of[h,g])p.on('pageerror',e=>errors.push(e.message));
 const url='http://localhost:8080/debug.html?debug=1&peerhost=127.0.0.1&peerport=9000&peerpath=/';await h.goto(url);await g.goto(url);
 await h.evaluate(()=>{const L=__pal.locker;L.eq.skin='galaxy';L.eq.hat='tophat';L.eq.bg='f_progress';L.owned.push('skin:galaxy','hat:tophat','bg:f_progress')});await h.click('[data-go=locker]');await h.waitForTimeout(400);await h.screenshot({path:__dirname+'/out/presentation/locker-desktop.png'});
 await g.evaluate(()=>{const L=__pal.locker;L.eq.skin='gknight';L.eq.hat='ghelm';L.eq.bg='f_japan';L.owned.push('skin:gknight','hat:ghelm','bg:f_japan')});await g.click('[data-go=locker]');await g.waitForTimeout(400);await g.screenshot({path:__dirname+'/out/presentation/locker-phone.png'});
 await h.click('[data-go=multi]');await h.fill('#mName','Motion Host');await h.click('#hostBtn');await h.waitForSelector('#pg-lobby:not([hidden])');const code=await h.textContent('#lCode');await g.click('[data-go=multi]');await g.fill('#mName','Motion Guest');await g.fill('#mCode',code);await g.click('#joinBtn');await g.waitForSelector('#pg-lobby:not([hidden])');await h.waitForTimeout(400);await h.evaluate(()=>__pal.lobbyReadyAll());await h.click('#lStart');await g.waitForFunction(()=>__pal.NET.inGame);
 const before=await h.evaluate(()=>({x:__pal.player.x,y:__pal.player.y}));await h.keyboard.down('d');await h.waitForTimeout(600);
 const moved=await h.evaluate(()=>({x:__pal.player.x,y:__pal.player.y,look:__pal.playerLook(__pal.player)})),remote=await g.evaluate(()=>{const p=[...__pal.players.values()].find(p=>p!==__pal.player);return {x:p.x,y:p.y,look:__pal.playerLook(p)}});
 await h.keyboard.up('d');await g.waitForFunction(()=>__pal.playerLook([...__pal.players.values()].find(p=>p!==__pal.player)).gaitWeight===0,null,{timeout:5000}).catch(()=>{});const stop=await g.evaluate(()=>__pal.playerLook([...__pal.players.values()].find(p=>p!==__pal.player)));
 assert.ok(Math.hypot(moved.x-before.x,moved.y-before.y)>.1,'host moved honestly');assert.ok(moved.look.gaitWeight>0,'host walking pose');assert.ok(remote.look.gaitWeight>0,'guest saw host walking');assert.equal(stop.gaitWeight,0,'remote pose settled');
 await h.screenshot({path:__dirname+'/out/presentation/game-host.png'});await g.screenshot({path:__dirname+'/out/presentation/game-guest.png'});
 // The guest also moves under the existing host movement validation.
 const g0=await g.evaluate(()=>({x:__pal.player.x,y:__pal.player.y}));await g.keyboard.down('a');await g.waitForTimeout(600);await g.keyboard.up('a');const g1=await g.evaluate(()=>({x:__pal.player.x,y:__pal.player.y}));assert.ok(Math.hypot(g1.x-g0.x,g1.y-g0.y)>.1,'guest moved');await h.waitForTimeout(600);
 const hostStop=await h.evaluate(()=>__pal.playerLook([...__pal.players.values()].find(p=>p!==__pal.player)));assert.equal(hostStop.gaitWeight,0);assert.deepEqual(errors,[]);
 // Exercise the shipped minified page too; opening the Locker alone never queues small gameplay sprites.
 const prod=await b.newPage({viewport:{width:1280,height:800}});prod.on('pageerror',e=>errors.push('production: '+e.message));
 await prod.addInitScript(()=>{const W=window.Worker;window.workerEvidence={completed:0,failed:0};window.Worker=class extends W{constructor(...args){super(...args);this.addEventListener('message',e=>{if(e.data.bitmap)window.workerEvidence.completed++;if(e.data.failed)window.workerEvidence.failed++});this.addEventListener('error',()=>window.workerEvidence.failed++)}}});
 await prod.goto('http://localhost:8080/index.html');await prod.click('[data-go=solo]');await prod.click('#startBtn');await prod.keyboard.down('d');await prod.waitForTimeout(700);await prod.keyboard.up('d');await prod.keyboard.down('a');await prod.waitForTimeout(700);await prod.keyboard.up('a');await prod.waitForTimeout(400);
 const productionWorkers=await prod.evaluate(()=>window.workerEvidence);assert.equal(productionWorkers.failed,0);assert.ok(productionWorkers.completed>0,'production minified worker completed');assert.deepEqual(errors,[]);
 fs.writeFileSync(__dirname+'/out/presentation/network.json',JSON.stringify({hostDisplacement:Math.hypot(moved.x-before.x,moved.y-before.y),hostWeight:moved.look.gaitWeight,remoteWeight:remote.look.gaitWeight,remoteStopped:stop.gaitWeight,guestDisplacement:Math.hypot(g1.x-g0.x,g1.y-g0.y),hostSawGuestStop:hostStop.gaitWeight,productionWorkers,errors},null,2));console.log('errors: none');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
