// Attachment / clipping samples for the articulated lower legs, large headgear, robes and downed poses.
const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>window.__pal);
 const result=await p.evaluate(()=>{const P=__pal,variants=[['skeleton','class'],['mummy','class'],['scarecrow','class'],['dracula','class'],['sheetghost','class'],['std','jackolantern'],['gclown','gclownhair'],['gpolice','pcap'],['gknight','ghelm']],bad=[],sheet=document.createElement('canvas');sheet.width=1080;sheet.height=variants.length*200;const sx=sheet.getContext('2d');sx.fillStyle='#bdc5b5';sx.fillRect(0,0,sheet.width,sheet.height);
 variants.forEach(([skin,hat],row)=>{for(let state=0;state<6;state++){const c=document.createElement('canvas');c.width=c.height=320;const x=c.getContext('2d',{willReadFrequently:true}),pose={...P.lookOf({skin,hat},['soldier','sniper','grenadier','quartermaster'][row%4]),gaitWeight:state===5?0:1,gaitDir:state===4?Math.PI/2:0,downed:state===5,nogun:state===5};P.paintWardrobeCharacter(x,pose,state===4?1.8:.65,1,4,160,260,state*Math.PI/2);
  const a=x.getImageData(0,0,320,320).data;let pixels=0,edge=0;for(let y=0;y<320;y++)for(let xx=0;xx<320;xx++){if(a[(y*320+xx)*4+3]>50){pixels++;if(!y||y===319||!xx||xx===319)edge++}}if(pixels<100||edge)bad.push(`${skin}/${state}: empty or clipped (${pixels}/${edge})`);
  sx.drawImage(c,state*180,row*200,180,180);sx.fillStyle='#142519';sx.font='11px sans-serif';sx.fillText(skin+' / '+(state===5?'downed':state===4?'strafe':'step '+state),state*180+5,row*200+190);
 }});return {bad,checked:variants.length*6,image:sheet.toDataURL()};});
 assert.deepEqual(result.bad,[]);assert.deepEqual(errors,[]);fs.mkdirSync(__dirname+'/out/presentation',{recursive:true});fs.writeFileSync(__dirname+'/out/presentation/pose-fit.png',Buffer.from(result.image.split(',')[1],'base64'));delete result.image;fs.writeFileSync(__dirname+'/out/presentation/pose-fit.json',JSON.stringify({...result,errors},null,2));console.log(JSON.stringify(result));console.log('errors: none');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
