const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const A='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',C='cccccccc-cccc-4ccc-cccc-cccccccccccc';
const users={[A]:{id:A,email:'test-a@example.invalid',is_anonymous:false,user_metadata:{pw:true,theme:'original'}},[B]:{id:B,email:'test-b@example.invalid',is_anonymous:false,user_metadata:{pw:true}},[C]:{id:C,is_anonymous:false,user_metadata:{pw:true}}};
const profiles=[{id:A,username:'Captain',cos:'gold|tophat|galaxy|skull'},{id:B,username:'Rook',cos:'neonclown|glitch|plasma|none'},{id:C,username:'Nova',cos:'std|class|std|none'}];
const L={owned:['skin:std','skin:gold','hat:class','hat:cap','hat:tophat','trail:std','trail:galaxy','fx:none','fx:skull'],eq:{skin:'gold',hat:'tophat',trail:'galaxy',fx:'skull'},cases:1,bag:{},shards:24,prog:0,st:{raids:8,wins:2,drops:30,endless:0,hardWins:0},imported:true};
const token=id=>Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id})).toString('base64url')+'.test';
const session=id=>({access_token:token(id),refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user:users[id]});
const writes=[];let failWrite=false,delaySearch=0;
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),ctx=await b.newContext({viewport:{width:1600,height:1000}}),errors=[];await ctx.route('https://puvjfhwxigxjpsvdwrwf.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname;let id;try{id=JSON.parse(Buffer.from(req.headers().authorization.split(' ')[1].split('.')[1],'base64url')).sub}catch{}let data={},status=200;if(path==='/auth/v1/user'){if(req.method()==='PUT'){writes.push(req.postDataJSON());if(failWrite){status=503;data={message:'offline'}}else{users[id].user_metadata={...users[id].user_metadata,...req.postDataJSON().data};data=users[id]}}else data=users[id]}else if(path==='/rest/v1/profiles'){if(url.searchParams.has('username')){if(delaySearch)await new Promise(r=>setTimeout(r,delaySearch));data=profiles.filter(p=>p.username.toLowerCase()===url.searchParams.get('username').slice(3).toLowerCase())}else{const ids=url.searchParams.get('id')||'';data=profiles.filter(p=>ids.includes(p.id))}}else if(path==='/rest/v1/lobbies')data=[{host_id:B,code:'ABCD',players:2,in_game:false,mode:'coop',name:"Rook's game"}];else if(path==='/rest/v1/rpc/get_my_locker')data=L;else{status=404;data={message:'unhandled'}}await route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)})});
const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(s=>localStorage.setItem('palisade.auth.v1',JSON.stringify(s)),session(A));const url='http://localhost:8080/debug.html?debug=1&cloud=1';await p.goto(url);await p.waitForFunction(()=>__pal.acct.state==='full');assert.equal(await p.textContent('#identityName'),'Captain');assert.match(await p.textContent('#identityState'),/SIGNED IN/);await p.click('[data-nav=multi]');await p.click('#friendsBtn');await p.waitForFunction(()=>!__pal.SOCIAL.loading);assert.equal(await p.inputValue('#mName'),'Captain');assert.equal(await p.locator('#mName').getAttribute('readonly'),'');
await p.fill('#friendName','Rook');await p.locator('#friendSearch button').click();await p.waitForSelector('#friendResult .friendRow');await p.locator('#friendResult').getByRole('button',{name:'SAVE',exact:true}).click();await p.waitForFunction(()=>!__pal.SOCIAL.busy&&__pal.SOCIAL.ids.length===1);assert.deepEqual(users[A].user_metadata.palisade_saved_players_v1,[B]);assert.equal(users[A].user_metadata.pw,true);assert.equal(users[A].user_metadata.theme,'original');assert.deepEqual(Object.keys(writes[0]),['data']);assert.deepEqual(Object.keys(writes[0].data),['palisade_saved_players_v1']);
await p.reload();await p.waitForFunction(()=>__pal.acct.state==='full');await p.click('[data-nav=multi]');await p.click('#friendsBtn');await p.waitForFunction(()=>!__pal.SOCIAL.loading&&__pal.SOCIAL.profiles.length===1);assert.match(await p.textContent('#savedPlayers'),/Rook/);assert.match(await p.textContent('#savedPlayers'),/IN LOBBY/);await p.screenshot({path:__dirname+'/out/signed-in-lobby.jpg',quality:85});
failWrite=true;await p.getByRole('button',{name:'Remove Rook from saved players'}).click();await p.waitForFunction(()=>!__pal.SOCIAL.busy);assert.deepEqual(users[A].user_metadata.palisade_saved_players_v1,[B]);assert.equal(await p.locator('#savedPlayers .friendRow').count(),1);failWrite=false;
await p.getByRole('button',{name:'Remove Rook from saved players'}).click();await p.waitForFunction(()=>!__pal.SOCIAL.busy&&__pal.SOCIAL.ids.length===0);assert.deepEqual(users[A].user_metadata.palisade_saved_players_v1,[]);
// A delayed result from an old account must not appear after switching accounts.
delaySearch=500;await p.fill('#friendName','Nova');await p.locator('#friendSearch button').click();await p.evaluate(s=>{__pal.acct.s=s;__pal.acct.name='Rook';__pal.renderIdentity()},session(B));await p.waitForTimeout(700);assert.equal(await p.locator('#friendResult .friendRow').count(),0);assert.equal(await p.textContent('#identityName'),'Rook');assert.equal(await p.locator('#savedPlayers .friendRow').count(),0);
assert.equal(await p.evaluate(()=>__pal.locker.shards),24);assert.deepEqual(await p.evaluate(()=>{const {bg,...eq}=__pal.locker.eq;return eq}),L.eq);assert.equal(errors.length,0);console.log(JSON.stringify({accountSync:true,reload:true,failedWritePreservesList:true,metadataPreserved:true,accountIsolation:true,lockerUnchanged:true}));console.log('errors: none');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
