// Versioned RPC, actual result/reel/equip UI and duplicate payout; all requests mocked.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'}),errors=[],calls=[];
let locker={owned:['skin:std','hat:class','hat:cap','trail:std','fx:none'],eq:{skin:'std',hat:'class',trail:'std',fx:'none'},cases:2,bag:{},shards:0,prog:0,st:{},rev:1,imported:true};
p.on('pageerror',e=>errors.push(e.message));await p.route('https://puvjfhwxigxjpsvdwrwf.supabase.co/**',async route=>{const req=route.request(),name=new URL(req.url()).pathname.split('/').pop(),body=req.postDataJSON()||{};calls.push(name);let data={};
if(/^open_cases_v096[24]$/.test(name)){assert.equal(body.p_case,'supply');assert.equal(body.p_quantity,1);const dup=locker.owned.includes('skin:sahur');locker.cases--;if(dup)locker.shards+=80;else locker.owned.push('skin:sahur');data={operation:body.p_operation,case:'supply',quantity:1,results:[{item:{id:'skin:sahur',cat:'skin',key:'sahur',name:'Tung Tung Tung Sahur',rarity:'u'},dup,shards:dup?80:0}],locker,retry:false};}   // v0.9.6.2 batch call
else if(name==='open_case_v0935'||name==='open_case_v094'){assert.equal(body.p_case,'supply');const dup=locker.owned.includes('skin:sahur');locker.cases--;if(dup)locker.shards+=80;else locker.owned.push('skin:sahur');data={case:'supply',item:{id:'skin:sahur',cat:'skin',key:'sahur',name:'Tung Tung Tung Sahur',rarity:'u'},dup,locker};}
else if(name==='equip'){assert.equal(body.p_item,'skin:sahur');locker.eq.skin='sahur';data=locker;}
else if(name==='get_my_locker')data=locker;
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>window.__pal);
await p.evaluate(L=>{const P=__pal;P.acct.s={access_token:'mock-test-only',refresh_token:'mock',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'11111111-1111-4111-8111-111111111111111',is_anonymous:true}};P.acct.state='guest';P.takeLocker(L);P.showPage('locker')},locker);
await p.click('[data-open=supply]');await p.click('#caseIntro');await p.waitForSelector('#caseResult:not([hidden])');assert.match(await p.textContent('#caseSub'),/ULTIMATE SKIN.*new/);assert.equal(await p.textContent('#caseName'),'Tung Tung Tung Sahur');await p.screenshot({path:__dirname+'/out/ultimate_cloud_result.png'});await p.click('#caseEquip');await p.waitForFunction(()=>__pal.locker.eq.skin==='sahur');
await p.click('[data-open=supply]');await p.click('#caseIntro');await p.waitForSelector('#caseResult:not([hidden])');assert.match(await p.textContent('#caseSub'),/already owned, \+80 shards/);assert.equal(await p.evaluate(()=>__pal.locker.shards),80);assert.equal(locker.cases,0);assert.ok(!calls.includes('open_case_of'));assert.equal(calls.filter(x=>/^open_cases_v096[24]$/.test(x)).length,2);assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/out/ultimate_cloud.json',JSON.stringify({calls,shards:locker.shards,cases:locker.cases,errors},null,2));console.log('Ultimate cloud result, equip and duplicate passed');console.log('errors: none');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
