const {PGlite}=require('@electric-sql/pglite'),{base,U}=require('./winter-db'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const db=new PGlite(),read=n=>fs.readFileSync(__dirname+'/../supabase/migrations/'+n,'utf8');await db.exec(base);await db.exec(read('20260930075446_palisade_v0938_all_boss_milestones.sql'));await db.exec(read('20260930141401_palisade_v0940_blitz.sql'));
// Winter catalog data has no dependency on room tables or reward receipts.
const winter=read('20261001081259_winter_whiteout.sql');await db.exec("insert into case_types(id,name,weights,shard_cost) values('winter','WINTER CASE','{\"c\":45,\"r\":32,\"e\":16,\"l\":6,\"g\":1}',14)");await db.exec(winter.slice(winter.indexOf('insert into public.cosmetics')));
const migration=read('20261001214620_winter_models.sql');await db.exec(migration);await db.exec(migration);await db.exec(`insert into lockers(user_id,bag,shards) values('${U}','{"winter":50}',100);set request.jwt.claim.sub='${U}'`);
const count=(await db.query("select count(*)::int n from cosmetics where box='winter'")).rows[0].n;assert.equal(count,37);
const rolls=[];for(const [id,r]of[['yulemaw','e'],['rednosedemolisher','l'],['gildedfrostborn','g']]){await db.exec(`create or replace function private.roll_rarity(w jsonb) returns text language sql set search_path='' as $$select '${r}'::text$$;update cosmetics set catalog_version=9 where box='winter' and rarity='${r}' and key<>'${id}'`);
 const v=(await db.query("select public.open_case_v0961('winter',null) r")).rows[0].r;assert.equal(v.item.id,'skin:'+id);rolls.push(v.item.id);await db.exec("update cosmetics set catalog_version=2 where catalog_version=9")}
// Old clients only see the pre-model catalog. Force Epic then remove all eligible old Epics:
await db.exec("create or replace function private.roll_rarity(w jsonb) returns text language sql set search_path='' as $$select 'e'::text$$");for(let n=0;n<30;n++){const v=(await db.query("select public.open_case_v094('winter',null) r")).rows[0].r;assert.notEqual(v.item.id,'skin:yulemaw')}
const c=(await db.query("select weights,shard_cost from case_types where id='winter'")).rows[0];assert.equal(c.shard_cost,14);assert.deepEqual(c.weights,{c:45,r:32,e:16,l:6,g:1});await db.close();console.log({count,rolls,oldClientRolls:30});console.log('errors: none');})().catch(e=>{console.error(e);process.exit(1)});
