const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),page=await browser.newPage({viewport:{width:1360,height:950}}),errs=[];page.on('pageerror',e=>errs.push(e.message));await page.goto('http://localhost:8080/debug.html?debug=1');await page.waitForFunction(()=>__pal?.COS);
 const result=await page.evaluate(()=>{const P=__pal,items=P.COS.filter(it=>it.collection==='winter'),out={counts:{},items:items.map(c=>({id:c.id,name:c.name,r:c.r,box:c.box,need:c.need,description:c.description,animated:!!c.animated||c.key==='aurorahalo'})),fit:[]};
  for(const c of items)out.counts[c.cat]=(out.counts[c.cat]||0)+1;out.animated=P.WINTER_BG.filter(v=>v[3]).length;out.goldTrail=items.filter(c=>c.cat==='trail'&&c.r==='g').length;out.goldFX=items.filter(c=>c.cat==='fx'&&c.r==='g').length;
  const cv=document.createElement('canvas');cv.id='winterProof';cv.width=1360;cv.height=930;cv.style='position:fixed;inset:0;z-index:9999;background:#14232e';document.body.append(cv);const c=cv.getContext('2d');c.fillStyle='#14232e';c.fillRect(0,0,1360,930);c.font='12px monospace';c.textAlign='center';
  const caption=(text,x,y)=>{const words=text.split(' '),split=Math.ceil(words.length/2);c.fillText(words.slice(0,split).join(' '),x,y);c.fillText(words.slice(split).join(' '),x,y+14)};
  P.WINTER_PAIRS.forEach((p,n)=>{const xx=68+n*135;for(const [j,skin]of[[0,p[0]],[1,'sahur']]){const look=P.lookOf({skin,hat:p[2],trail:'std',fx:'none',bg:'campfire'},'soldier');out.fit.push({skin,hat:p[2],allowed:P.headwearAllowed(skin,p[2]),field:look.winterHat});P.paintWardrobeCharacter(c,look,.6,1,2.6,xx,155+j*165,false)}c.fillStyle='#e4eff1';caption(p[1],xx,179);caption(p[3],xx,340)});
  P.WINTER_BG.forEach(([id,nm],i)=>{const x=(i%5)*272,y=370+Math.floor(i/5)*155;c.save();c.translate(x,y);P.BGS[id].draw(c,268,132,2);c.restore();c.fillStyle='#e4eff1';c.fillText(nm,x+134,y+146)});
  P.WINTER_TRACERS.forEach(([id,nm],i)=>{const x=100+i*215;P.traceSeg(c,x+55,720,x-55,720,P.TRAILS[id],4,2,false);c.fillStyle='#e4eff1';c.fillText(nm,x,750)});
  P.WINTER_FX.forEach(([id,nm],i)=>{const x=100+i*215;P.paintFinish(c,id,.35,1.5,x,835);c.fillStyle='#e4eff1';c.fillText(nm,x,900)});
  const blank=document.createElement('canvas');blank.width=200;blank.height=140;const bc=blank.getContext('2d');out.motion=[];for(const [id,nm,r,animated]of P.WINTER_BG){bc.clearRect(0,0,200,140);P.BGS[id].draw(bc,200,140,1);const a=blank.toDataURL();bc.clearRect(0,0,200,140);P.BGS[id].draw(bc,200,140,3);out.motion.push({id,animated,changed:a!==blank.toDataURL()})}
  // Every headgear is exercised in all classes, angles and downed poses using the worker-compatible rig.
  out.poses=0;for(const [skin,hat]of P.WINTER_PAIRS.map(p=>[p[0],p[2]]).concat(P.WINTER_PAIRS.map(p=>['sahur',p[2]])))for(const cls of Object.keys(P.CLASSES))for(let a=0;a<8;a++)for(const downed of[false,true]){P.paintWardrobeCharacter(bc,{...P.lookOf({skin,hat},cls),downed},a*Math.PI/4,0,1.4,100,125,false);out.poses++}
  return out;
 });assert.deepEqual(result.counts,{skin:13,hat:10,trail:6,fx:6,bg:10});assert.equal(result.animated,4);assert.equal(result.goldTrail,2);assert.equal(result.goldFX,2);assert.equal(result.items.length,45);result.fit.forEach(r=>{assert.ok(r.allowed);assert.equal(r.field,r.hat)});result.motion.forEach(r=>assert.equal(r.changed,r.animated));assert.deepEqual(errs,[]);
 await page.screenshot({path:__dirname+'/out/winter_collection.png'});fs.writeFileSync(__dirname+'/out/winter_cosmetics.json',JSON.stringify(result,null,2));await browser.close();console.log({counts:result.counts,poses:result.poses});console.log('errors: none');
})().catch(e=>{console.error(e);process.exit(1)});
