const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const A='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',B='bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',inv='cccccccc-cccc-4ccc-accc-cccccccccccc',profiles={[A]:{id:A,username:'SnowHost',cos:'std|class|std|none'},[B]:{id:B,username:'SnowFriend',cos:'sahur|ushanka|snowstreak|snowpuff'}},locker={owned:['skin:std','hat:class','trail:std','fx:none'],eq:{skin:'std',hat:'class',trail:'std',fx:'none'},cases:0,bag:{},st:{raids:0},shards:0,prog:0,imported:true};
let room=null,pending=false,answers=0,sends=0,gate=null;
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,args:['--disable-features=WebRtcHideLocalIpsWithMdns']}),errors=[],calls=[];
 const make=async id=>{const ctx=await browser.newContext({viewport:{width:390,height:844}});await ctx.route('https://puvjfhwxigxjpsvdwrwf.supabase.co/**',async r=>{const req=r.request(),url=new URL(req.url()),fn=url.pathname.split('/').pop(),p=req.postDataJSON()||{};let data={},status=200;calls.push(fn);
  if(url.pathname==='/auth/v1/user')data={id,email:'fixture@example.invalid',is_anonymous:false,user_metadata:{pw:true}};
  else if(fn==='profiles')data=[profiles[id]];else if(fn==='lobbies')data=[];
  else if(fn==='get_my_locker')data=locker;else if(fn==='social_state')data={friends:[profiles[id===A?B:A]],incoming:[],outgoing:[],notes:[],unseen:pending&&id===B?1:0,invites:pending&&id===B?[{id:inv,user:profiles[A],created_at:new Date().toISOString(),expires_at:new Date(Date.now()+300000).toISOString(),room}]:[]};
  else if(fn==='room_register'){room=p.p;data={registered:true}}
  else if(fn==='lobby_invite_send'){pending=true;sends++;data={id:inv}}
  else if(fn==='lobby_invite_answer'){answers++;if(gate){gate.entered=true;await gate.wait}if(p.p_accept){data={...room,status:'accepted'};pending=false}else{data={status:'declined'};pending=false}}
  else if(fn==='notes_seen')data={seen:1};else if(fn==='claim_match_reward')data={locker,cases:{},unlocked:[],held:0};else{status=404;data={message:'fixture unhandled '+fn}}
  await r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
 });const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));const token=Buffer.from('{}').toString('base64url')+'.'+Buffer.from(JSON.stringify({sub:id})).toString('base64url')+'.fixture';await page.addInitScript(s=>{localStorage.setItem('palisade.auth.v1',JSON.stringify(s));localStorage.setItem('palisade.cfg.v1',JSON.stringify({listGame:false}))},{access_token:token,refresh_token:'fixture',expires_at:Math.floor(Date.now()/1000)+3600,user:{id,is_anonymous:false,email:'fixture@example.invalid',user_metadata:{pw:true}}});await page.goto('http://localhost:8080/debug.html?cloud=1&debug=1&peerhost=127.0.0.1&peerport=9000&peerpath=/');await page.waitForFunction(()=>__pal.acct.state==='full');return page};
 const H=await make(A),G=await make(B);await H.evaluate(()=>{__pal.cfg.listGame=false;__pal.pick.mode='campaign'});await H.click('[data-nav=multi]');await H.click('#hostBtn');await H.waitForFunction(()=>__pal.NET.mode==='host');await H.click('#friendsBtn');await H.locator('#friendList').getByRole('button',{name:'INVITE',exact:true}).click();await G.evaluate(()=>__pal.friendsPoll());await G.click('#friendsBtn');await G.click('[data-ft=mail]');assert.match(await G.textContent('#mailList'),/OPERATION WHITEOUT/);await G.locator('.lobbyInvite').getByRole('button',{name:'DECLINE',exact:true}).click();assert.equal(answers,1);
 await H.locator('#friendList').getByRole('button',{name:'INVITE',exact:true}).click();await G.evaluate(()=>__pal.friendsPoll());await G.locator('.lobbyInvite').getByRole('button',{name:'ACCEPT',exact:true}).click();await G.waitForFunction(()=>__pal.NET.mode==='guest');assert.equal(answers,2);assert.equal(await H.evaluate(()=>__pal.NET.roster.length),2);
 // Receiving a notification while in another room does not move the recipient.
 pending=true;await G.evaluate(()=>__pal.friendsPoll());await G.click('#friendsBtn');await G.click('[data-ft=mail]');await G.locator('.lobbyInvite').getByRole('button',{name:'ACCEPT',exact:true}).click();assert.equal(answers,2);assert.equal(await G.evaluate(()=>__pal.NET.mode),'guest');assert.match(await G.textContent('#socialStatus'),/leaves your current/);assert.ok(await G.locator('.lobbyInvite').getByRole('button',{name:'LEAVE & JOIN',exact:true}).isVisible());
 const box=await G.locator('#friendsDrop').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=391);await G.screenshot({path:__dirname+'/out/winter_friend_invite.png'});
 await G.click('#friendsClose');await H.click('#friendsClose');await H.click('#lStart');await G.waitForFunction(()=>!__pal.demo&&document.getElementById('menu').hidden);await G.click('#pauseBtn');await G.click('#pFriendsBtn');assert.ok(await G.locator('#mailList').isVisible());await G.screenshot({path:__dirname+'/out/winter_in_game_invite.png'});
 let release;gate={entered:false,wait:new Promise(r=>release=r)};await G.locator('.lobbyInvite').getByRole('button',{name:'LEAVE & JOIN',exact:true}).click();for(let n=0;n<20&&!gate.entered;n++)await G.waitForTimeout(50);assert.ok(gate.entered);
 await G.evaluate(()=>{__pal.game.gid='different-run'});release();await G.waitForFunction(()=>!__pal.FR.busy);assert.equal(await G.evaluate(()=>__pal.NET.mode),'guest');assert.equal(await G.evaluate(()=>__pal.demo),false);assert.match(await G.textContent('#socialStatus'),/Joining was canceled/);
 pending=true;await G.evaluate(()=>__pal.friendsPoll());await G.locator('.lobbyInvite').getByRole('button',{name:'ACCEPT',exact:true}).click();gate={entered:false,wait:new Promise(r=>release=r)};await G.locator('.lobbyInvite').getByRole('button',{name:'LEAVE & JOIN',exact:true}).click();for(let n=0;n<20&&!gate.entered;n++)await G.waitForTimeout(50);assert.ok(gate.entered);
 await G.evaluate(id=>{__pal.acct.s.user.id=id;__pal.renderIdentity()},A);assert.equal(await G.evaluate(()=>__pal.FR.busy),false);release();await G.waitForTimeout(500);assert.equal(await G.evaluate(()=>__pal.NET.mode),'guest');assert.equal(await G.evaluate(()=>__pal.demo),false);assert.equal(await G.evaluate(()=>__pal.FR.invites.length),0);
 assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/out/winter_invites.json',JSON.stringify({sends,answers,privateRoom:true,actualPeerJoin:true,deliberateLeaveConfirmation:true,inGameMailbox:true,changedSessionCancelsJoin:true,accountSwitchIgnoresOldAcceptance:true,viewport:[390,844],calls:[...new Set(calls)]},null,2));console.log('Private invite, decline, real PeerJS accept, in-game mailbox and account/session guards passed');console.log('errors: none');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
