const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const url='http://localhost:8080/debug.html?peerhost=127.0.0.1&peerport=9000&peerpath=/&debug=1';
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,args:['--disable-features=WebRtcHideLocalIpsWithMdns']}),H=await b.newPage({viewport:{width:1100,height:760}}),G=await(await b.newContext()).newPage(),errors=[],out={};for(const p of[H,G]){p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.waitForFunction(()=>__pal?.NET)}
 await H.click('[data-nav=multi]');await H.click('[data-setup=rules]:visible');await H.click('#setupSheet [data-m5=campaign]');await H.click('#setupDone');await H.click('#hostBtn');await H.waitForFunction(()=>__pal.NET.mode==='host');const code=await H.textContent('#lCode');await G.click('[data-nav=multi]');await G.fill('#mCode',code);await G.click('#joinBtn');await G.waitForFunction(()=>__pal.NET.mode==='guest');await H.evaluate(()=>__pal.lobbyReadyAll());await H.click('#lStart');await G.waitForFunction(()=>!__pal.demo&&__pal.game.mode==='campaign'&&__pal.game.joinHeld===0);
 await H.evaluate(()=>{const P=__pal;for(const p of P.players.values())p.hp=p.max=1e9;P.core.hp=P.core.max=P.qm.hp=P.qm.max=1e9;P.game.timer=9999;P.game.wave=3;P.player.up.d=3;P.player.upS='30000';P.kitUp(P.player);P.player.ammoEq=['shock',''];P.game.dellLv=4;P.campaignAdvance();P.skipMapEvac()});await G.waitForFunction(()=>__pal.game.chapter===1&&__pal.game.map==='river');out.river=await G.evaluate(()=>({chapter:__pal.game.chapter,map:__pal.game.map,dell:__pal.game.dellLv,hostUp:__pal.players.get('host').up.d,hostAmmo:__pal.players.get('host').ammoEq[0]}));
 await H.evaluate(()=>{const P=__pal;P.game.wave=6;P.campaignAdvance();P.skipMapEvac();P.game.wave=9;P.campaignAdvance();P.skipMapEvac();P.game.timer=9999;P.addFrost(4.5,8.5);P.spawnBoss('rime');const e=P.enemies.find(e=>e.boss==='rime');e.st=101;e.stT=e.stM=1.5;e.lx=4.5;e.ly=8.5});await G.waitForFunction(()=>__pal.game.chapter===3&&__pal.frostFields.length&&__pal.enemies.some(e=>e.boss==='rime'));out.frost=await G.evaluate(()=>({map:__pal.game.map,coreZ:__pal.heightAt(__pal.core.i+.5,__pal.core.j+.5),field:__pal.frostFields.length,bossZ:__pal.enemies.find(e=>e.boss==='rime').z}));
 out.hostMove=await H.evaluate(()=>{const P=__pal,[peer,c]=[...P.NET.conns.entries()].find(([,c])=>c.pid),p=P.players.get(c.pid),put=(x,y,tx,ty)=>{p.x=x;p.y=y;c.moveBudget=2;c.moveAt=performance.now();P.hostData(peer,{t:'i',x:tx,y:ty,tp:p.tp,ax:0,ay:-1,f:0,n:0,a:0});return{x:p.x,y:p.y}};return{cliff:put(8.5,5.4,8.5,4.6),ramp:put(4.5,5.5,4.5,5.25)}});assert.deepEqual(out.hostMove.cliff,{x:8.5,y:5.4});assert.deepEqual(out.hostMove.ramp,{x:4.5,y:5.25});
 // New guest arrives directly at the current chapter and receives the hazard state.
 const L=await(await b.newContext()).newPage();L.on('pageerror',e=>errors.push(e.message));await L.goto(url);await L.click('[data-nav=multi]');await L.fill('#mCode',code);await L.click('#joinBtn');await L.waitForFunction(()=>!__pal.demo&&__pal.game.chapter===3&&__pal.frostFields.length);out.late=await L.evaluate(()=>({map:__pal.game.map,chapter:__pal.game.chapter,joinHeld:__pal.game.joinHeld}));
 // Fill the real PeerJS room to six players before the shared finale.
 const crew=[];for(let i=0;i<3;i++){const p=await(await b.newContext()).newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.click('[data-nav=multi]');await p.fill('#mCode',code);await p.click('#joinBtn');await p.waitForFunction(()=>!__pal.demo&&__pal.game.chapter===3);crew.push(p)}await H.waitForFunction(()=>__pal.players.size===6);out.sixPlayers=await Promise.all([H,G,L,...crew].map(p=>p.evaluate(()=>({players:__pal.players.size,map:__pal.game.map,chapter:__pal.game.chapter}))));assert.ok(out.sixPlayers.every(p=>p.players===6&&p.chapter===3));
 await H.evaluate(()=>{const P=__pal;P.game.wave=12;P.game.phase='build';P.startRaid();P.game.fb.t=29.8});await G.waitForFunction(()=>__pal.game.fb?.evac);out.finale=await G.evaluate(()=>({wave:__pal.game.wave,max:__pal.game.fb.max,t:Math.round(__pal.game.fb.t),site:__pal.game.fb.evac}));
 await H.evaluate(()=>{const P=__pal,E=P.game.fb.evac,g=[...P.players.values()].find(p=>p.id!=='host');window.pin=setInterval(()=>{g.x=E.x;g.y=E.y;g.tp++},30)});await G.waitForFunction(()=>__pal.player.out,null,{timeout:20000});await H.evaluate(()=>{clearInterval(window.pin);__pal.game.fb.t=.1});await G.waitForFunction(()=>__pal.game.phase==='over');await H.waitForTimeout(1000);out.results=await Promise.all([H,G].map(p=>p.evaluate(()=>({title:document.getElementById('overTitle').textContent,mode:__pal.game.mode,maps:['yard','river','quarry','frost'].map(m=>__pal.locker.st['map_'+m]||0),winter:__pal.locker.bag.winter||0}))));
 fs.writeFileSync(__dirname+'/out/winter_network.json',JSON.stringify(out,null,2));assert.equal(out.river.dell,4);assert.equal(out.river.hostUp,3);assert.equal(out.river.hostAmmo,'shock');assert.equal(out.frost.coreZ,2);assert.equal(out.finale.wave,13);assert.equal(out.finale.max,18);assert.equal(out.results[0].title,'LEFT BEHIND');assert.equal(out.results[1].title,'EVACUATED');assert.deepEqual(out.results[1].maps,[3,3,3,4]);assert.ok(out.results[1].winter>=1);assert.deepEqual(errors,[]);
 fs.writeFileSync(__dirname+'/out/winter_network.json',JSON.stringify(out,null,2));await G.screenshot({path:__dirname+'/out/winter_network.png'});console.log(out);console.log('errors: none');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
