// Behavioral coverage for v0.9.6.1. Run through run_targeted.ps1.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://localhost:8080/dev/test/out/baseline-debug.html?debug=1');await p.waitForFunction(()=>window.__pal);
const baseline=await p.evaluate(()=>{const P=__pal;P.demo=false;P.newGame(null,'',{mods:['alone','laststand']});P.game.phase='raid';P.game.wave=1;P.game.queue=['rifle'];P.game.spawn=999;P.player.alive=false;P.player.downed=true;P.player.rt=1e6;P.game.paused=false;for(let n=0;n<120;n++)P.update(1/60);return{phase:P.game.phase,rt:P.player.rt,core:P.core.hp,qmGone:P.qm.gone}});assert.equal(baseline.phase,'raid');assert.ok(baseline.rt>999900);
await p.goto('http://localhost:8080/debug.html?debug=1');await p.waitForFunction(()=>window.__pal);
const result=await p.evaluate(()=>{const P=__pal,out={checks:[]},ok=(n,v)=>{if(!v)throw Error(n);out.checks.push(n)},reset=(mods=[])=>{P.demo=false;P.NET.mode='solo';P.pick.map='yard';P.pick.mode='endless';P.newGame(null,'',{mods});P.game.paused=true;P.enemies.length=0;P.bullets.length=0;P.game.phase='raid';P.game.wave=1;P.game.queue=['rifle'];P.game.spawn=999},down=()=>{P.player.alive=false;P.player.downed=true;P.player.rt=1e6};
reset(['alone','laststand']);down();const hp=P.core.hp;ok('unrecoverable modifier pair',P.checkDeadEnd()&&P.game.phase==='over'&&P.game.endReason==='deadend');ok('core remains intact',P.core.hp===hp);const shards=P.locker.shards;P.showOver();ok('rewards exactly once',P.locker.shards===shards);
reset(['alone']);down();P.player.rt=8;ok('finite respawn survives',!P.checkDeadEnd());reset(['laststand']);down();P.qm.x=P.player.x+.4;P.qm.y=P.player.y;ok('reachable assisted revive survives',!P.checkDeadEnd());P.qm.alive=false;ok('downed quartermaster terminal',P.checkDeadEnd());
reset(['alone','laststand']);down();P.game.queue=[];ok('committed raid completion survives',!P.checkDeadEnd());P.charges.push({x:2,y:2,fuse:2});ok('finite post-raid hazards preserve preparation recovery',!P.checkDeadEnd());reset(['alone','laststand']);down();const mate=P.makePlayer('mate','Mate','soldier',1);P.players.set('mate',mate);ok('alive teammate preserves recovery',!P.checkDeadEnd());mate.alive=false;mate.downed=true;mate.rt=1e6;ok('whole co-op crew terminates',P.checkDeadEnd());reset(['laststand']);down();const tk=Math.floor(P.player.x)+Math.floor(P.player.y)*P.N;P.walls.fill(P.makeWall(2,false));P.walls[tk]=null;P.qm.x=2.5;P.qm.y=2.5;ok('unreachable living Delgado cannot soft-lock',P.checkDeadEnd());reset(['alone','laststand']);down();P.NET.mode='guest';ok('guest cannot finalize',!P.checkDeadEnd());reset(['alone','laststand']);P.game.mode='blitz';P.game.waves=15;P.game.wave=15;P.game.fb={t:20,n:15,max:15,evac:{x:2,y:2,r:1},done:false};P.player.out=true;const stranded=P.makePlayer('stranded','Stranded','soldier',1);stranded.alive=false;stranded.downed=true;stranded.rt=1e6;P.players.set(stranded.id,stranded);ok('evac crew dead end finalizes',P.checkDeadEnd());ok('extracted player keeps personal victory',P.blitzResult(P.player)==='evac'&&P.blitzResult(stranded)==='left'&&P.game.won);
reset();P.game.phase='build';P.walls.fill(null);P.player.x=P.core.i+3.5;P.player.y=P.core.j-3.5;P.qm.x=P.core.i+.5;P.qm.y=P.core.j+.5;P.qm.mats=[1000,1000,1000];ok('host selects defend',P.setQMMode('defend'));const layout=P.qmLayout();out.layout=layout;ok('4x4 or3x3 perimeter',layout.length>=7&&layout.length<=12&&layout.every(t=>t.i!==P.core.i||t.j!==P.core.j));
const tick=()=>{for(let n=0;n<1800;n++)P.updateQM(1/60)};tick();out.build={count:layout.filter(t=>P.walls[t.k]).length,status:P.qm.status,mats:P.qm.mats.slice()};ok('constructs perimeter with paid resources',out.build.count>=7&&P.qm.mats[0]<1000);P.game.wave=5;P.startBuild();P.game.paused=true;tick();ok('raid5 construction tier',layout.filter(t=>P.walls[t.k]).every(t=>P.walls[t.k].mat>=1));const paid=P.qm.mats[1];P.setQMMode('follow');P.setQMMode('defend');tick();ok('switching does not duplicate upgrades',P.qm.mats[1]===paid);P.game.wave=10;P.startBuild();P.game.paused=true;tick();ok('raid10 tier capped at metal',layout.filter(t=>P.walls[t.k]).every(t=>P.walls[t.k].mat===2));P.setQMMode('follow');tick();ok('follow stays near host',Math.hypot(P.qm.x-P.player.x,P.qm.y-P.player.y)<2.5);P.NET.mode='guest';ok('guest mode command rejected',!P.setQMMode('follow'));P.NET.mode='solo';
reset();P.game.phase='build';P.walls.fill(null);const corner=(P.core.i+2)+(P.core.j+2)*P.N;P.setTerr(corner,1);P.qm.layoutAnchor='';ok('terrain selects3x3 fallback',P.qmLayout().length<=8&&P.qm.layoutSize===3);P.qm.mats=[0,0,0];P.setQMMode('defend');ok('empty inventory does not build free walls',P.qmCommandJob().name!=='construct');reset(['alone']);ok('absent Delgado has no orders',!P.setQMMode('defend'));reset();P.game.pvp='ffa';ok('PvP has no orders',!P.setQMMode('defend'));
// Actual collision path, using a clear tile and a frontal bullet.
reset();P.walls.fill(null);let pos;for(let y=2;y<P.N-2&&!pos;y++)for(let x=2;x<P.N-2;x++)if(!P.solidTileHook(x,y)&&!P.solidTileHook(x-1,y)){pos=[x+.5,y+.5];break}let e=P.spawnEnemyAt('shield',...pos);e.hp=e.max=10000;e.aim={x:-1,y:0};const shot=(damage=1,ap=false,side=false)=>{P.bullets.push({id:10000+Math.random(),x:e.x-.45,y:e.y,vx:10,vy:0,dist:0,range:10,dmg:damage,team:0,own:P.player.id,shot:1,ammo:ap?[['ap',0]]:[],z0:.7,zSlope:0});if(side)e.aim={x:1,y:0};P.updateBulletsHook(.03);e.aim={x:-1,y:0}};
shot(1);const n=e.shieldHitsLeft,h=e.hp;shot(500);ok('low/high damage cost one hit',n===19&&e.shieldHitsLeft===18&&e.hp===h);shot(1,false,true);ok('rear hit does not wear shield',e.shieldHitsLeft===18&&e.hp<h);const hpAP=e.hp;shot(10,true);ok('AP consumes one with penetration',e.shieldHitsLeft===17&&e.hp<hpAP);
const spent=e.shieldHitsLeft;P.explode(e.x,e.y,1,1,P.player.id);P.hurtEnemyHook(e,5,P.player.id);ok('nonbullet damage leaves shield budget',e.shieldHitsLeft===spent);const contact={id:60000};P.shieldBulletHit(e,contact);const once=e.shieldHitsLeft;P.shieldBulletHit(e,contact);ok('same bullet contact is deduplicated',e.shieldHitsLeft===once);const base=e.shieldHitsLeft;for(let n=0;n<5;n++)shot(1);ok('five contacting shotgun pellets cost five hits',e.shieldHitsLeft===base-5);const partial=e.shieldHitsLeft;for(let n=0;n<5;n++)P.bullets.push({id:70000+n,x:e.x-.45,y:e.y+(n<2?0:1),vx:10,vy:0,dist:0,range:10,dmg:1,team:0,own:P.player.id,shot:2,z0:.7,zSlope:0});P.updateBulletsHook(.03);ok('only two contacting pellets wear the shield',e.shieldHitsLeft===partial-2);P.bullets.length=0;e.shieldHitsLeft=2;const before=e.hp;shot();shot();ok('last ordinary hit blocked',e.shieldBroken&&e.shieldHitsLeft===0&&e.hp===before);shot();ok('broken shield admits later bullets',e.hp<before);const snap=P.makeSnap(true);P.applySnap(snap);const guest=P.enemies.find(x=>x.id===e.id);ok('snapshot retains shield break',guest.shieldBroken&&guest.shieldHitsLeft===0&&guest.shieldHitsMax===20);
out.shield={left:e.shieldHitsLeft,broken:e.shieldBroken};for(const damage of[1,1000]){P.enemies.length=0;e=P.spawnEnemyAt('shield',...pos);e.hp=e.max=1e6;e.aim={x:-1,y:0};for(let n=0;n<19;n++)shot(damage);ok('shield survives19 hits at damage'+damage,e.shieldHitsLeft===1&&!e.shieldBroken&&e.hp===1e6);shot(damage);ok('exactly20 hits break at damage'+damage,e.shieldHitsLeft===0&&e.shieldBroken&&e.hp===1e6)}
const cv=document.createElement('canvas');cv.width=960;cv.height=650;cv.id='newModels';cv.style='position:fixed;inset:0;z-index:9999;background:#132330';document.body.append(cv);const c=cv.getContext('2d');c.fillStyle='#132330';c.fillRect(0,0,960,650);c.font='13px monospace';c.textAlign='center';let poses=0;
for(const [row,m]of P.WINTER_MODELS.entries()){for(let a=0;a<4;a++){const look=P.lookOf({skin:m[0],hat:'none'},'soldier');P.paintWardrobeCharacter(c,look,a*Math.PI/2,2,3.6,120+a*240,180+row*210,true);c.fillStyle='#e4eef0';c.fillText(m[1]+' / '+['front','right','back','left'][a],120+a*240,200+row*210)}for(const cls of Object.keys(P.CLASSES))for(let a=0;a<4;a++)for(const downed of[false,true]){P.paintWardrobeCharacter(c,{...P.lookOf({skin:m[0],hat:'none'},cls),downed},a*Math.PI/2,2,1,-200,-200,true);poses++}}for(const m of P.WINTER_MODELS){const look=P.lookOf({skin:m[0],hat:'class'},'soldier'),v=document.createElement('canvas');v.width=220;v.height=170;const ctx=v.getContext('2d');P.drawFig(ctx,220,170,{...look,detail:true,syncRender:true},2,null,150);const full=v.toDataURL();ctx.clearRect(0,0,220,170);P.drawFig(ctx,220,170,{...look,detail:false,syncRender:true},2,null,150);ok('full model in compact preview '+m[0],full===v.toDataURL());ok('saved cosmetic ID parses '+m[0],P.parseCos(m[0]+'|class|std|none').skin===m[0])}out.poses=poses;return out});
await p.screenshot({path:__dirname+'/out/new_winter_models.png'});assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/out/winter_upgrade.json',JSON.stringify({baseline,...result,errors},null,2));console.log(result);await b.close();console.log('errors: none');})().catch(e=>{console.error(e);process.exit(1)});
