// Use the real production page and real service worker; localhost is a secure
// browser context, so this test registers the HTTPS production worker explicitly.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM||undefined}),ctx=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),p=await ctx.newPage(),errors=[],out={};p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://localhost:8080/index.html');assert.equal(await p.evaluate(()=>typeof window.__pal),'undefined');await p.evaluate(async()=>{await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready});await p.reload();await p.waitForFunction(()=>!!navigator.serviceWorker.controller);out.cached=await p.evaluate(()=>caches.keys());
 await ctx.setOffline(true);await p.reload();await p.click('[data-nav=solo]');await p.click('[data-setup=rules]:visible');await p.click('#setupSheet [data-m5=campaign]');await p.click('#setupDone');await p.click('#startBtn');await p.waitForFunction(()=>document.getElementById('menu').hidden);out.campaign={label:await p.textContent('#phaseLab'),tip:await p.textContent('#tip')};assert.match(out.campaign.label,/CH 1/);
 await p.click('#armBtn');await p.click('#armAmmoTab');assert.equal(await p.locator('[data-arm-ammo]').count(),4);await p.click('#armClose');await p.click('#pauseBtn');await p.click('#quitBtn');
 await p.click('[data-nav=solo]');await p.click('[data-setup=rules]:visible');await p.click('#setupSheet [data-m5="5"]');await p.click('#setupDone');await p.click('[data-setup=map]:visible');await p.click('#mapCards [data-map=frost]');await p.click('#setupDone');await p.click('#startBtn');await p.waitForFunction(()=>document.getElementById('menu').hidden);out.frost=await p.textContent('#phaseLab');assert.equal(out.frost,'BUILD');await p.screenshot({path:__dirname+'/out/winter_frostpeak_mobile.png'});assert.deepEqual(errors,[]);out.errors=errors;out.offline=true;fs.writeFileSync(__dirname+'/out/winter_offline.json',JSON.stringify(out,null,2));console.log(out);console.log('errors: none');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
